// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjizgoryfnllxntulqpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaXpnb3J5Zm5sbHhudHVscXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTE0OTksImV4cCI6MjA2NzkyNzQ5OX0.eXeugUyEZQ7uZF4PsGhOOdS24wCLIdr9ce-g2f1Su6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});